# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: 'Secret Json Secrets'
description: 'Hide secrets defined in a secret json'
inputs:
  secret_json:
    description: 'A secret json containing secrets'
    required: true
  key_pattern:
    description: 'Keys matching this pattern will be hidden'
    required: false
    default: 'KEY|SECRET'
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: hide.sh '${{ inputs.secret_json }}' '${{ inputs.key_pattern }}'
      shell: bash
