# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: 'Secret Json Secrets'
description: 'Hide secrets defined in a secret json'
inputs:
  secret_json:
    description: 'A secret json containing secrets'
    required: true
  ignore_case:
    description: 'Determine case-insensitive matching'
    required: false
    default: '1'
  key_pattern:
    description: 'Keys matching this pattern will be hidden'
    required: false
    default: 'KEY|SECRET|TOKEN'
  val_pattern:
    description: 'Values matching this pattern will be hidden'
    required: false
    default: ''
  verbose:
    description: 'Print debug messages'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: 'Init'
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: 'Hide'
      run: hide.sh '${{ inputs.secret_json }}' '${{ inputs.key_pattern }}' '${{ inputs.val_pattern }}' '${{ inputs.ignore_case }}' '${{ inputs.verbose }}'
      shell: bash
